# Generated by Django 5.1.7 on 2025-03-07 10:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetDefectueux',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_produit', models.CharField(db_index=True, max_length=100)),
                ('date_inspection', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('DEFECTUEUX', 'Défectueux'), ('OK', 'OK')], db_index=True, max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
