# Generated by Django 5.1.7 on 2025-05-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0003_analyseia'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyseia',
            name='image_annotee',
            field=models.TextField(blank=True, null=True),
        ),
    ]
